# Generated by Django 5.0.1 on 2024-02-12 08:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_maker', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=64, unique=True)),
                ('contact_data', models.TextField(blank=True, null=True)),
                ('dating_date', models.DateField(auto_now_add=True)),
                ('discount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=128)),
                ('provider_inn', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('dating_date', models.DateField(auto_now_add=True)),
                ('contact_person', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_data', models.TextField(default='')),
                ('contact_person_2', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_data_2', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=32)),
                ('car_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagedb.carmaker')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(default='XXXXXXXXXXXXXXXXX', max_length=17, unique=True)),
                ('number_plate', models.CharField(default='A123AA198', max_length=12, unique=True)),
                ('year', models.CharField(default='2020', max_length=4)),
                ('color', models.CharField(default='Unknown', max_length=32)),
                ('images', models.ImageField(blank=True, null=True, upload_to='%Y-%m-%d/')),
                ('ocr', models.CharField(choices=[('YES', 'Text recognition has been performed'), ('NO', 'It was not recognized')], default='NO', max_length=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='pagedb.carmodel')),
                ('owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pagedb.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=32)),
                ('spare_name', models.CharField(max_length=128)),
                ('comments', models.TextField(blank=True, null=True)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('price_for', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagedb.car')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagedb.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('date_issue', models.DateField(blank=True, max_length=8)),
                ('price_for_buyer', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('status', models.CharField(choices=[('IN_WORK', 'in working'), ('FOR_ISSUE', 'ready to be issued'), ('FINISHED', 'finished'), ('CANCELED', 'canceled')], default='IN_WORK', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagedb.car')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagedb.spare')),
            ],
        ),
    ]
