# Generated by Django 5.0.1 on 2024-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagetwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ocr',
            field=models.CharField(choices=[('YES', 'Фотография СТС распознана'), ('NO', 'Фотография СТС НЕ распознана')], default='NO', max_length=5),
        ),
    ]
